name: PR Title Validation
on:
  pull_request:
    types: [opened, edited, reopened]
jobs:
  validate-title-convention:
    name: Validate Title Convention
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-pr-title@v1.0.1
        with:
          regex: '^(Feature|Bug|Hotfix|Refactor|Build|Test)(\(\w+\))?:\s([a-zA-Z0-9]{1,10}-\d+|NO-JIRA)\s.+'
          prefix_case_sensitive: false
  validate-jira-issue-key-exists:
    name: Validate Jira Issue Key Exists
    if: contains(github.event.pull_request.title, 'NO-JIRA') == false
    runs-on: ubuntu-latest
    steps:
      - uses: cakeinpanic/jira-description-action@v0.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          jira-token: '${{ secrets.JIRA_USER }}:${{ secrets.JIRA_TOKEN }}'
          jira-base-url: 'https://alicorpdigital.atlassian.net'
          fail-when-jira-issue-not-found: 'true'